# Generated by Django 5.1.15 on 2026-07-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_stock_source',
            },
        ),
        migrations.CreateModel(
            name='StockLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('on_hand', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='inventory.stocksourcemodel')),
            ],
            options={
                'db_table': 'inventory_stock_level',
                'constraints': [models.UniqueConstraint(fields=('sku', 'source'), name='uniq_stock_level_sku_source'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='ck_stock_level_reserved_le_on_hand')],
            },
        ),
    ]
