# Generated by Django 5.1.15 on 2026-07-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_default_source_and_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksourcemodel',
            options={'permissions': [('manage_stock_source', 'Can manage stock sources (create, set/adjust stock)')]},
        ),
    ]
