# Generated by Django 5.1.15 on 2026-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stocksourcemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('backorderable', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('backordered', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_stock_policy',
            },
        ),
    ]
