# Generated by Django 5.1.15 on 2026-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallengeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('purpose', models.CharField(choices=[('registration', 'registration'), ('password_reset', 'password_reset')], max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('max_attempts', models.PositiveSmallIntegerField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'identity_otp_challenge',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone_number', 'purpose', '-created_at'], name='identity_ot_phone_n_25d1d7_idx')],
            },
        ),
    ]
