# Generated by Django 5.1.15 on 2026-06-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_otpchallengemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_access', 'Can administer access (assign roles and channel scope)')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
