# Generated by Django 5.1.15 on 2026-06-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('plain_text', 'plain_text'), ('number', 'number'), ('boolean', 'boolean'), ('dropdown', 'dropdown')], max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
                'db_table': 'catalog_attribute',
                'ordering': ('code',),
                'permissions': [('manage_catalog', 'Can manage the catalog (attributes, product types, products)')],
            },
        ),
        migrations.CreateModel(
            name='AttributeChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.attributemodel')),
            ],
            options={
                'db_table': 'catalog_attribute_choice',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('attribute', 'value'), name='uniq_choice_value_per_attribute')],
            },
        ),
    ]
