# Generated by Django 5.1.15 on 2026-06-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product type',
                'verbose_name_plural': 'product types',
                'db_table': 'catalog_product_type',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductTypeAttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_type_links', to='catalog.attributemodel')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_links', to='catalog.producttypemodel')),
            ],
            options={
                'db_table': 'catalog_product_type_attribute',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('product_type', 'attribute'), name='uniq_attribute_per_product_type')],
            },
        ),
    ]
