# Generated by Django 5.1.15 on 2026-06-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_producttypemodel_producttypeattributemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.producttypemodel')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'catalog_product',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='catalog.attributemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_product_attribute_value',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('product', 'attribute'), name='uniq_value_per_product_attribute')],
            },
        ),
    ]
