# Generated by Django 5.1.15 on 2026-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariantmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypeattributemodel',
            options={'ordering': ('kind', 'position')},
        ),
        migrations.AddField(
            model_name='producttypeattributemodel',
            name='kind',
            field=models.CharField(choices=[('product', 'product'), ('variant', 'variant')], default='product', max_length=16),
        ),
    ]
