# Generated by Django 5.1.15 on 2026-06-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_producttypeattributemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantAttributeValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_values', to='catalog.attributemodel')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.productvariantmodel')),
            ],
            options={
                'db_table': 'catalog_product_variant_attribute_value',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('variant', 'attribute'), name='uniq_value_per_variant_attribute')],
            },
        ),
    ]
