# Generated by Django 5.1.15 on 2026-06-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariantattributevaluemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.productvariantmodel')),
            ],
            options={
                'db_table': 'catalog_product_variant_media',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('variant', 'url'), name='uniq_media_url_per_variant')],
            },
        ),
    ]
