# Generated by Django 5.1.15 on 2026-06-29 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='catalog.categorymodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_product_category',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('product', 'category'), name='uniq_category_per_product')],
            },
        ),
    ]
