# Generated by Django 5.1.15 on 2026-06-29 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_collectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='catalog.collectionmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_links', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_collection_product',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('collection', 'product'), name='uniq_product_per_collection')],
            },
        ),
    ]
