# Generated by Django 5.1.15 on 2026-06-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_collectionproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRuleConditionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'equals'), ('not_equals', 'not_equals')], max_length=16)),
                ('value', models.CharField(max_length=1024)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_conditions', to='catalog.attributemodel')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_conditions', to='catalog.collectionmodel')),
            ],
            options={
                'db_table': 'catalog_collection_rule_condition',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('collection', 'attribute', 'operator', 'value'), name='uniq_condition_per_collection_rule')],
            },
        ),
    ]
