# Generated by Django 5.1.15 on 2026-06-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_collectionruleconditionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_slug', models.SlugField(max_length=64)),
                ('currency_code', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.productvariantmodel')),
            ],
            options={
                'db_table': 'catalog_variant_price',
                'ordering': ('channel_slug',),
                'constraints': [models.UniqueConstraint(fields=('variant', 'channel_slug'), name='uniq_price_per_variant_channel')],
            },
        ),
    ]
