# Generated by Django 5.1.15 on 2026-06-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_variantpricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.productvariantmodel')),
            ],
            options={
                'db_table': 'catalog_variant_stock',
            },
        ),
    ]
