# Generated by Django 5.1.15 on 2026-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_variantstockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
