# Generated by Django 5.1.15 on 2026-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_delete_variantstockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
