# Generated by Django 5.1.15 on 2026-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_productvariantmodel_weight_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='tax_class',
            field=models.CharField(default='standard', max_length=64),
        ),
    ]
