# Generated by Django 5.1.15 on 2026-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=64)),
                ('actor', models.CharField(blank=True, max_length=64, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['resource_type', 'resource_id', '-occurred_at'], name='audit_log_resourc_eb69c7_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_log_action_a9f1a6_idx')],
            },
        ),
    ]
