# Generated by Django 5.1.15 on 2026-06-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelmodel',
            options={'ordering': ('slug',), 'permissions': [('manage_channel', 'Can manage channels (create, activate, deactivate)')], 'verbose_name': 'channel', 'verbose_name_plural': 'channels'},
        ),
    ]
