# Generated by Django 5.1.15 on 2026-07-02 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('channel_slug', models.SlugField(max_length=64)),
                ('currency_code', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(max_length=16)),
                ('placed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'order_order',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderLineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.ordermodel')),
            ],
            options={
                'db_table': 'order_order_line',
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['owner', '-id'], name='idx_order_owner_recent'),
        ),
        migrations.AddConstraint(
            model_name='orderlinemodel',
            constraint=models.UniqueConstraint(fields=('order', 'sku'), name='uniq_line_sku_per_order'),
        ),
    ]
