# Generated by Django 5.1.15 on 2026-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_line1",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_phone_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_postal_code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_province",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_recipient_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
