# Generated by Django 5.1.15 on 2026-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_manage_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_method_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_method_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
