# Generated by Django 5.1.15 on 2026-07-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordermodel_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
