# Generated by Django 5.1.15 on 2026-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermodel_tax_amount_ordermodel_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='fulfillment_carrier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='fulfillment_tracking_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='fulfillment_tracking_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_is_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_recipient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(max_length=24),
        ),
    ]
