# Generated by Django 5.1.15 on 2026-07-05 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'db_table': 'wallet_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('reason', models.CharField(max_length=64)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source_reference', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.walletmodel')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'db_table': 'wallet_transaction',
                'ordering': ('-id',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_reference__isnull', False)), fields=('wallet', 'source_reference'), name='uniq_wallet_transaction_source')],
            },
        ),
    ]
