# Generated by Django 5.1.15 on 2026-07-05 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('order_number', models.CharField(max_length=40)),
                ('guest_token', models.CharField(blank=True, max_length=64, null=True)),
                ('method', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment_payment',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['owner', 'order_number'], name='idx_payment_owner_order'), models.Index(fields=['guest_token', 'order_number'], name='idx_payment_guest_order')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('guest_token__isnull', True), ('owner__isnull', False)), models.Q(('guest_token__isnull', False), ('owner__isnull', True)), _connector='OR'), name='payment_exactly_one_owner'), models.UniqueConstraint(condition=models.Q(('status__in', ['authorized', 'captured', 'pending'])), fields=('order_number',), name='uniq_active_payment_per_order')],
            },
        ),
    ]
