# Generated by Django 5.1.15 on 2026-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
