# Generated by Django 5.1.15 on 2026-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmodel_gateway_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
