# Generated by Django 5.1.15 on 2026-07-01 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_slug', models.SlugField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
                'db_table': 'cart_cart',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CartLineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.cartmodel')),
            ],
            options={
                'db_table': 'cart_cart_line',
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='cartmodel',
            constraint=models.UniqueConstraint(fields=('owner', 'channel_slug'), name='uniq_cart_per_owner_channel'),
        ),
        migrations.AddConstraint(
            model_name='cartlinemodel',
            constraint=models.UniqueConstraint(fields=('cart', 'sku'), name='uniq_line_sku_per_cart'),
        ),
    ]
