# Generated by Django 5.1.15 on 2026-07-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartmodel',
            name='uniq_cart_per_owner_channel',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='guest_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cartmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_token__isnull', True), ('owner__isnull', False)), models.Q(('guest_token__isnull', False), ('owner__isnull', True)), _connector='OR'), name='cart_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='cartmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'channel_slug'), name='uniq_cart_per_user_channel'),
        ),
        migrations.AddConstraint(
            model_name='cartmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_token__isnull', False)), fields=('guest_token', 'channel_slug'), name='uniq_cart_per_guest_channel'),
        ),
    ]
