# Generated by Django 5.1.15 on 2026-07-02 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=40, unique=True)),
                ('recipient_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, default='', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'address_address',
                'ordering': ('-is_default', '-id'),
                'indexes': [models.Index(fields=['owner', '-id'], name='idx_address_owner_recent')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='uniq_default_address_per_owner')],
            },
        ),
    ]
